- name: 'Projects'
  link: '/projects'
- name: 'Gathering'
  link: '/gathering'
- name: 'beverage'
  link: '/lunch-beverage'
- name: 'Sweets'
  link: '/lunch_sweets'
- name: 'Drinks'
  link: '/afterwork-drinks'
- name: 'Apero'
  link: '/apero'
- name: 'About'
  link: '/about'
